n1 = (input( 'Digite algo: '))
print('Dados do caractere:')
print('Tipo primitivo', type(n1))
print('Numeral', n1.isnumeric())
print('Alfabetica', n1.isalpha())
print('Maiúscula', n1.isupper())
print('Miniúscula', n1.islower())
print('Alfanumérica', n1.isalnum())
print('Título',n1.istitle())
print('É digito numérico',n1.isdigit())